application: tc-builder
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: tcbuilder.py

libraries:
- name: jinja2
  version: latest