application: tc-builder
version: 2013-02-11
runtime: python27
#runtime: python
api_version: 1
threadsafe: false

handlers:
- url: /assets
  static_dir: assets

- url: .*
  script: tcbuilder.py

libraries:
- name: jinja2
  version: latest